### ISSUE TITLE
Pop up window "you need to login" moves a text

### ISSUE THREAD

**Issue by jmoravec01** [matej-kaska/ujepsoft#5]
In the video you can see that pop up window moves the text a bit (maybe change pop ups to position: absolute).

https://github.com/matej-kaska/ujepsoft/assets/91320507/e89db06a-017a-4f4d-b77d-9cde31a4b650

css right now:
```
.modal-content {
    display: flex;
    flex-direction: column;
    background-color: #fefefe;
    padding: 1rem;
    border: 1px solid #888;
    border-radius: 4px;
    width: -moz-fit-content;
    width: fit-content;
    align-items: flex-end;
    justify-content: space-between;
}
```

**Comment by jmoravec01** [comment]
+ found that Shein does not have dynamic titles

**Comment by matej-kaska** [comment]
It's because, when you click the link, you are redirected on the page. When you are on the new page, ProtectedRoute will redirect you back to the "/" and Offers have to load again. I have fixed it now, so when you click on the link, app will get logged in status and then it will redirect you to the page.

So please test it

**Comment by jmoravec01** [comment]
Fixed.
